
import React from 'react';
import { EquityData, formatCurrency, formatPercentage, formatNumber } from '../utils/calculatorUtils';

interface PDFTemplateProps {
  data: EquityData;
}

// Note: This component is not rendered directly but used as a template for PDF generation
const PDFTemplate: React.FC<PDFTemplateProps> = ({ data }) => {
  return (
    <div className="pdf-container">
      <div className="header">
        <h1>Equity Dilution Calculation Report</h1>
        <p className="date">Generated on: {new Date().toLocaleDateString()}</p>
      </div>
      
      <div className="section">
        <h2>Summary</h2>
        <table className="summary-table">
          <thead>
            <tr>
              <th>Parameter</th>
              <th>Before Investment</th>
              <th>After Investment</th>
              <th>Change</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Company Valuation</td>
              <td>{formatCurrency(data.companyValuation)}</td>
              <td>{formatCurrency(data.postMoneyValuation)}</td>
              <td>+{formatCurrency(data.newInvestmentAmount)}</td>
            </tr>
            <tr>
              <td>Total Shares</td>
              <td>{formatNumber(data.initialShares)}</td>
              <td>{formatNumber(data.totalSharesAfterDilution)}</td>
              <td>+{formatNumber(data.newSharesIssued)}</td>
            </tr>
            <tr>
              <td>Your Equity Percentage</td>
              <td>{formatPercentage(data.equityPercentage)}</td>
              <td>{formatPercentage(data.newEquityPercentage)}</td>
              <td>{formatPercentage(data.newEquityPercentage - data.equityPercentage)}</td>
            </tr>
            <tr>
              <td>Your Equity Value</td>
              <td>{formatCurrency(data.equityValueBeforeDilution)}</td>
              <td>{formatCurrency(data.equityValueAfterDilution)}</td>
              <td>{formatCurrency(data.equityValueAfterDilution - data.equityValueBeforeDilution)}</td>
            </tr>
          </tbody>
        </table>
      </div>
      
      <div className="section">
        <h2>Understanding Equity Dilution</h2>
        <p>
          Equity dilution occurs when a company issues new shares, which reduces the ownership percentage of existing shareholders. 
        </p>
        <p>
          In this case, your equity percentage has changed from {formatPercentage(data.equityPercentage)} to {formatPercentage(data.newEquityPercentage)} due to the new investment of {formatCurrency(data.newInvestmentAmount)}.
        </p>
        <p>
          However, while your percentage ownership has decreased, the value of your equity has actually changed from {formatCurrency(data.equityValueBeforeDilution)} to {formatCurrency(data.equityValueAfterDilution)} because the overall company valuation has increased.
        </p>
      </div>
      
      <div className="footer">
        <p>Generated by Equity-Viz-Calculator-Pro | equity-viz-calculator-pro.com</p>
      </div>
    </div>
  );
};

export default PDFTemplate;
