
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { EquityData, formatCurrency, formatPercentage, formatNumber } from './calculatorUtils';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

export const generateEquityDilutionPDF = (data: EquityData): Promise<Blob> => {
  return new Promise((resolve) => {
    // Create a new PDF document
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(20);
    doc.setTextColor(36, 94, 79); // Dark Green
    doc.text('Equity Dilution Calculation Report', 105, 20, { align: 'center' });
    
    // Add date
    doc.setFontSize(10);
    doc.setTextColor(51, 51, 51); // Charcoal
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 105, 30, { align: 'center' });
    
    // Add horizontal line
    doc.setDrawColor(122, 201, 167); // Mint Green
    doc.setLineWidth(0.5);
    doc.line(20, 35, 190, 35);
    
    // Add summary section
    doc.setFontSize(14);
    doc.setTextColor(36, 94, 79); // Dark Green
    doc.text('Summary', 20, 45);
    
    // Add company details
    doc.setFontSize(11);
    doc.setTextColor(51, 51, 51); // Charcoal
    
    // Create summary table
    doc.autoTable({
      startY: 50,
      head: [['Parameter', 'Before Investment', 'After Investment', 'Change']],
      body: [
        ['Company Valuation', 
         formatCurrency(data.companyValuation), 
         formatCurrency(data.postMoneyValuation), 
         `+${formatCurrency(data.newInvestmentAmount)}`],
        ['Total Shares', 
         formatNumber(data.initialShares), 
         formatNumber(data.totalSharesAfterDilution), 
         `+${formatNumber(data.newSharesIssued)}`],
        ['Your Equity Percentage', 
         formatPercentage(data.equityPercentage), 
         formatPercentage(data.newEquityPercentage), 
         formatPercentage(data.newEquityPercentage - data.equityPercentage)],
        ['Your Equity Value', 
         formatCurrency(data.equityValueBeforeDilution), 
         formatCurrency(data.equityValueAfterDilution), 
         formatCurrency(data.equityValueAfterDilution - data.equityValueBeforeDilution)]
      ],
      theme: 'grid',
      headStyles: { 
        fillColor: [36, 94, 79], 
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      alternateRowStyles: { 
        fillColor: [248, 248, 248]
      },
      columnStyles: {
        0: { fontStyle: 'bold' }
      }
    });
    
    // Add dilution explanation
    const startY = (doc as any).lastAutoTable.finalY + 15;
    
    doc.setFontSize(14);
    doc.setTextColor(36, 94, 79); // Dark Green
    doc.text('Understanding Equity Dilution', 20, startY);
    
    doc.setFontSize(11);
    doc.setTextColor(51, 51, 51); // Charcoal
    
    const dilutionText = 
      `Equity dilution occurs when a company issues new shares, which reduces the ownership percentage of existing shareholders. 
      
      In this case, your equity percentage has changed from ${formatPercentage(data.equityPercentage)} to ${formatPercentage(data.newEquityPercentage)} due to the new investment of ${formatCurrency(data.newInvestmentAmount)}.
      
      However, while your percentage ownership has decreased, the value of your equity has actually changed from ${formatCurrency(data.equityValueBeforeDilution)} to ${formatCurrency(data.equityValueAfterDilution)} because the overall company valuation has increased.`;
      
    const splitDilutionText = doc.splitTextToSize(dilutionText, 170);
    doc.text(splitDilutionText, 20, startY + 10);
    
    // Add footer
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Equity-Viz-Calculator-Pro | equity-viz-calculator-pro.com', 105, 285, { align: 'center' });
    
    // Get the PDF as a blob
    const pdfBlob = doc.output('blob');
    resolve(pdfBlob);
  });
};

export const downloadPDF = async (data: EquityData): Promise<void> => {
  const pdfBlob = await generateEquityDilutionPDF(data);
  const url = URL.createObjectURL(pdfBlob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `Equity_Dilution_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
